services:
  musicalo:
    image: alvaromolrui/musicalo:latest
    container_name: musicalo
    restart: unless-stopped
    environment:
      # Navidrome Configuration
      - NAVIDROME_URL=${NAVIDROME_URL}
      - NAVIDROME_USERNAME=${NAVIDROME_USERNAME}
      - NAVIDROME_PASSWORD=${NAVIDROME_PASSWORD}
      
      # ListenBrainz Configuration
      - LISTENBRAINZ_USERNAME=${LISTENBRAINZ_USERNAME}
      - LISTENBRAINZ_TOKEN=${LISTENBRAINZ_TOKEN}
      
      # Last.fm Configuration
      - LASTFM_API_KEY=${LASTFM_API_KEY}
      - LASTFM_USERNAME=${LASTFM_USERNAME}
      
      # Gemini Configuration
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      
      # Telegram Bot Configuration
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_WEBHOOK_URL=${TELEGRAM_WEBHOOK_URL}
      - TELEGRAM_ALLOWED_USER_IDS=${TELEGRAM_ALLOWED_USER_IDS}
      
      # Application Configuration
      - DEBUG=${DEBUG}
      - HOST=${HOST}
      - PORT=${PORT}
    
    ports:
      - "8000:8000"
    
    volumes:
      # Volumen para logs persistentes
      - logs:/app/logs
      # Volumen para configuración (opcional)
      - config:/app/config
    
    networks:
      - musicalo-network
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Límites de recursos
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Servicio opcional: Nginx como proxy reverso
  nginx:
    image: nginx:alpine
    container_name: musicalo-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - musicalo
    networks:
      - musicalo-network
    profiles:
      - nginx  # Solo se ejecuta si se especifica el perfil

networks:
  musicalo-network:
    driver: bridge

volumes:
  logs:
    driver: local
  config:
    driver: local
